version: '3.4'
services:
  db:
    image: postgres
    tmpfs: /var/lib/postgresql/data

  super_graph:
    image: dosco/super-graph:latest
    environment:
      GO_ENV: "development"
    depends_on:
      - db
    ports:
      - "8080:8080"
    
  rails_app:
    image: dosco/super-graph-demo:latest
    environment:
      RAILS_ENV: "development"
    tmpfs: /app/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
      - super_graph