# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
    - make gen
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

nfpms:
  - homepage: https://graphjin.com
    description: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
    license: "Apache 2"
    maintainer: Vikram Rangnekar <twitter.com/dosco>
    formats:
    - deb
    - rpm

brews:
  - tap:
      owner: dosco
      name: graphjin
    homepage: https://graphjin.com
    description: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler." 
    license: "Apache 2"
    skip_upload: auto

scoop:
  bucket:
    owner: dosco
    name: graphjin
  commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: https://graphjin.com
  description: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler."
  license: "Apache 2"

snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: "Build APIs in 5 minutes. An automagical GraphQL to SQL compiler"
    description: |
      GraphJin gives you a high performance GraphQL API without you having to write any code. GraphQL is automagically compiled into an efficient SQL query. Use it either as a library or a standalone service.
    grade: stable
    confinement: classic
    publish: true