no_trace: false
debounce: 300 # if rule has no debounce, this will be used instead
ignore: \.git/
trig: [start, run] # will run on start
rules:
  - name: start
  - name: run
    match: \.go$
    ignore: web|examples|docs|_test\.go$
    command: go run main.go serve
  - name: test
    match: _test\.go$
    command: go test -cover {PKG}
