version: "3.4"
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      target: go-build
    environment:
      GO_ENV: "development"
      CGO_ENABLED: 0
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ./examples/webshop/config:/app/config
    working_dir: /app
    command: wtc
    depends_on:
      - db
      # - rails_app
    # - redis
