version: '3.4'
services:
  db:
    image: postgres
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      
  rails_app:
    image: dosco/super-graph-demo:latest
    environment:
      RAILS_ENV: "development"
    tmpfs: /app/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db
      
  super_graph:
    image: dosco/super-graph:latest
    environment:
      GO_ENV: "development"
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rails_app