version: "3.4"
services:
  # Postgres DB
  db:
    image: postgres:12
    tmpfs: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  rails_app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tmpfs: /app/tmp/pids
    ports:
      - "3000:3000"
    depends_on:
      - db

  api:
    image: dosco/super-graph:latest
    environment:
      GO_ENV: "development"
    volumes:
      - ./config:/config
      - ./keys:/keys/
    ports:
      - "8080:8080"
    depends_on:
      - db
